config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :permission_classes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :technician_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment
  resources :shows
  resources :vendors, only: [:new, :create, :edit, :update, :show]
  resources :sessions, only: [:new ,:destroy]
  resources :users
  
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  post '/equipment_bookings/:id' => 'equipment_bookings#increment'
  post '/users/set_permissions' => 'users#set_permissions'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    belongs_to :vendor
    has_many :equipment_bookings
    has_many :shows, through: :equipment_bookings

    validates :name, :quantity, :category, :sub_category, :vendor, presence: true
    validates_uniqueness_of :name, scope: :manufacturer 

    def created_at_display
        self.created_at.localtime.strftime("%b %-d %Y %l:%M %p")
    end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
    before_action :can_create_equipment, only: [:new, :create, :edit, :update, :destroy]

    def index
        @equipment = @current_user.vendor.equipment
        @categories = @equipment.map {|e| e.category}.uniq        
    end

    def show
        @equipment = Equipment.find(params[:id])
        return redirect_to equipment_index_path unless @equipment.vendor == current_user.vendor
    end

    def new        
        @equipment = Equipment.new(category: params[:category])
    end

    def create
        @equipment = Equipment.new(equipment_params.merge(vendor: current_user.vendor))
        return render :new unless @equipment.save
        redirect_to equipment_index_path
    end

    def edit
        @equipment = Equipment.find(params[:id])
        return redirect_to equipment_index_path unless @equipment.vendor == current_user.vendor
    end

    def update
        @equipment = Equipment.find(params[:id])
        @equipment.update(equipment_params)
        redirect_to equipment_path(@equipment)
    end

    def destroy
        @equipment = Equipment.find(params[:id])
        @equipment.destroy
        redirect_to equipment_index_path
    end

    private

    def equipment_params
        params.require(:equipment).permit(:name, :manufacturer, :quantity, :category, :sub_category)
    end

    def can_create_equipment
        if !current_user.permission_class.create_equipment
        flash[:alert] = "You dont have permission to access and edit inventory"
        return redirect_to request.referrer unless request.referrer == nil
        redirect_to '/'
        end
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/edit.html.erb
<% if @equipment.errors.any? %>
        <ul class= "alert alert-danger">
          <% @equipment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    
<%= form_for @equipment do |f| %>
    <%=f.label :name %><br>
    <%=f.text_field :name %><br>

    <%=f.label :manufacturer %><br>
    <%=f.text_field :manufacturer %><br>

    <%=f.label 'Quantity Owned' %><br>
    <%=f.number_field :quantity %><br>

    <%=f.label :category %><br>
    <%=f.text_field :category %><br>

    <%=f.label "Sub-Category" %><br>
    <%=f.text_field :sub_category %><br>

    <%=f.submit "Submit"%>
<% end %>

app/views/equipment/index.html.erb
<%= link_to "Add Equipment", new_equipment_path %>
<% @categories.each do |cat|%>

<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
        <tr>
            <th>Equipment Name</th>
            <th>Manufacturer</th>
            <th>Quantity Owned</th>
            <th>Category</th>
            <th>SubCategory</th>
        </tr>
    </thead>
    <tbody>
<% @equipment.where(category: cat).each do |e| %>
    <tr> 
    <td><%= link_to e.name, equipment_path(e) %></td>
    <td> <%= e.manufacturer%> </td>
    <td> <%= e.quantity %> </td>
    <td> <%= e.category %> </td>
    <td> <%= e.sub_category %> </td>
    </tr>
<% end %>
</tbody>
</table>
<%if @permission.create_equipment %>
<%= link_to "Add #{cat} Equipment", new_equipment_path(category: cat) %>
<%end%>

<%end%>

app/views/equipment/new.html.erb
<% if @equipment.errors.any? %>
        <ul class= "alert alert-danger">
          <% @equipment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

<h3>Add equipment to inventory:</h3>
<%= form_for @equipment do |f| %>
    <%=f.label :name %><br>
    <%=f.text_field :name %><br>

    <%=f.label :manufacturer %><br>
    <%=f.text_field :manufacturer %><br>

    <%=f.label 'Quantity Owned' %><br>
    <%=f.number_field :quantity %><br>

    <%=f.label :category %><br>
    <%=f.text_field :category %><br>

    <%=f.label "Sub-Category" %><br>
    <%=f.text_field :sub_category %><br>

    <%=f.submit "Submit"%>
<% end %>

app/views/equipment/show.html.erb
<h1><%= @equipment.name %></h1>

<% if !flash[:alert].nil? %> 
   <div class= "alert alert-danger">
   <%= flash[:alert] %>
   </div>
<% end %>


<h3>Category: <%= "#{@equipment.category} > #{@equipment.sub_category}" %> </h3>
<h3>Quantity owned: <%= @equipment.quantity %></h3>
<h3>Manufactured by: <%= @equipment.manufacturer %></h3>
<%if @permission.create_equipment %>
<%= link_to 'Edit', edit_equipment_path(@equipment) %>
<%= link_to 'Delete', equipment_path(@equipment), method: "delete", data: { confirm: "Are you sure you want to delete #{@equipment.name}?" }%>
<%end%>