config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :permission_classes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :technician_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment
  resources :shows
  resources :vendors, only: [:new, :create, :edit, :update, :show]
  resources :sessions, only: [:new ,:destroy]
  resources :users
  
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  post '/equipment_bookings/:id' => 'equipment_bookings#increment'
  post '/users/set_permissions' => 'users#set_permissions'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :vendor
    belongs_to :permission_class
    has_many :technician_bookings
    has_many :shows, through: :technician_bookings

    validates :username, :first_name, :last_name, :password, :permission_class, :vendor_id, presence: true
    validates :username, uniqueness: {scope: :vendor_id, message: "is already in use by someone at your company"}
    
    
    has_secure_password
    
    def full_name
        "#{self.first_name} #{self.last_name}"
    end

    def full_name_and_title
        "#{self.permission_class.title} - #{self.full_name}"
    end

    def bookable?
        self.permission_class.bookable
    end

    def call_time_display
        self.call_time.localtime.strftime("%b %-d %Y %l:%M %p")
    end

    def out_time_display
        self.out_time.localtime.strftime("%b %-d %Y %l:%M %p")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :can_create_users, only: [:new, :create]
    # before_action :verify_self, only: [:update, :edit]

    def index
        users
    end

    def new        
        @user = User.new
        @permissions = @current_user.vendor.permission_classes
    end

    def create
        @permissions = @current_user.vendor.permission_classes
        @user = User.new(user_params.merge(vendor: @current_user.vendor))
        return  render :new unless @user.save
        redirect_to users_path
    end

    def show        
        @user = User.find(params[:id])
        return redirect_to users_path unless @user.vendor == current_user.vendor  
        @gigs = @user.technician_bookings.order(:call_time)        
    end

    def edit
        @user = User.find(params[:id])
        return redirect_to users_path unless @user.vendor == current_user.vendor
        @permissions = @user.vendor.permission_classes  
    end

    def update
        if params[:id] == 'set_title'
            user = User.find(permission_params[:id])
            user.update_attribute(:permission_class_id, permission_params[:permission_class_id])
            return render permission_classes_path
        end
        @user = User.find(params[:id])
        @permissions = @user.vendor.permission_classes
        return render :edit unless @user.update(user_params)
        redirect_to user_path(@user)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end  

    private
    
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :password, :password_confirmation, :permission_class_id)
    end

    def permission_params
        params.require(:user).permit(:permission_class_id, :id)
    end

    def can_create_users
        if !current_user.permission_class.create_users
        flash[:alert] = "You dont have permission to create users"
        return redirect_to request.referrer unless request.referrer == nil
        redirect_to '/'
        end
      end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<% if @user.errors.any? %>
        <ul class= "justify-content-center alert-info text-danger">
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>


<%= form_for @user do |f| %>

<h3>Edit <%=@user.username.titleize%> user info</h3>

  <%=f.label :username %><br>
  <%=f.text_field :username%><br>
    
    <% if @current_user.id == @user.id%>
        <%=f.label :password %><br>
        <%=f.password_field :password%><br>
    

        <%=f.label :password_confirmation %><br>
        <%=f.password_field :password_confirmation%><br>
    <%end%>

    <% if @permission.create_users%>
        <%=f.label :Permissions %><br>
        <%=f.collection_select :permission_class_id, @permissions, :id, :title%><br>
    <%end%>

<%=f.submit "Submit"%>

<%end%>

app/views/users/index.erb
<% if !flash[:alert].nil? %> 
   <div class= "alert alert-danger">
   <%= flash[:alert] %>
   </div>
<% end %>

<table class="table table-striped table-bordered table-sm">
  <thead class="thead-dark">
    <tr>
    <th>Username</th>
    <th>Full Name</th>
    <th>Job Title</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td> <%= link_to "@#{user.username}", user_path(user) %></td> 
        <td> <%=user.full_name%> </td>
        <td> <%=user.permission_class.title%> </td>
     </tr>
  <% end %>
  </tbody>
</table>
<%if @permission.create_users%>
<%= link_to 'Add User', new_user_path %>
<%end%>

app/views/users/new.erb
<% if @user.errors.any? %>
        <ul class= "alert alert-danger">
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>


<%= form_for @user do |f| %>

<h3>Create A New User</h3>

  <%=f.label :username %><br>
  <%=f.text_field :username%><br>

  <%=f.label :first_name %><br>
  <%=f.text_field :first_name%><br>

  <%=f.label :last_name %><br>
  <%=f.text_field :last_name%><br>

  <%=f.label :password %><br>
  <%=f.password_field :password%><br>

  <%=f.label :password_confirmation %><br>
  <%=f.password_field :password_confirmation%><br>
  
  <%=f.label :title %><br>
  <%=f.collection_select :permission_class_id, @permissions, :id, :title%><br>

<%=f.submit "Submit"%>
<%end%>

app/views/users/show.erb
<h1><%= @user.full_name %></h1>
<h2>@<%=@user.username%></h2>
<h3><%= @user.permission_class.title %></h3> 
  
<% if @user.permission_class.bookable %>
  <table class="table table-striped table-bordered table-sm">
    <caption style='caption-side: top'>Schedule</caption>
    <thead class="thead-dark">
      <tr>
        <th>Show</th>
        <th>Venue</th>
        <th>Call Time</th>
        <th>Out Time</th>
      </tr>
    </thead>
    <tbody>
    <% @gigs.each do |gig| %>
      <tr>
        <td> <%= link_to gig.show.name, show_path(gig.show) %></td> 
        <td> <%= gig.show.venue %></td> 
        <td> <%= gig.call_time_display %></td> 
        <td> <%=gig.out_time_display%> </td>
      </tr> 
    <% end %>
    </tbody>
  </table>


<%end%>

<% if @current_user.id == @user.id %>
<%= link_to 'Edit User', edit_user_path(@user)%>
<%end%>
<% if @current_user.permission_class.create_users %>
<%= link_to 'Delete User', user_path(@user), method: "delete", data: { confirm: "Are you sure?" }%>
<%end%>