config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :permission_classes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :technician_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment
  resources :shows
  resources :vendors, only: [:new, :create, :edit, :update, :show]
  resources :sessions, only: [:new ,:destroy]
  resources :users
  
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  post '/equipment_bookings/:id' => 'equipment_bookings#increment'
  post '/users/set_permissions' => 'users#set_permissions'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vendor.rb
class Vendor < ApplicationRecord
    has_many :shows
    has_many :users
    has_many :permission_classes
    has_many :equipment

    validates :name, :address, :url, :contact_email, :phone_number, presence: true


    after_create :create_owner_permission

    def create_owner_permission
        admin = PermissionClass.create(title: "admin", vendor: self, create_users: true, create_equipment:true, create_show:true, book_technician:true, book_equipment:true, bookable: false, admin: true )
    end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    def new
        @vendor = Vendor.new
    end

    def show
        @vendor = Vendor.find(params[:id])
        return redirect_to '/' unless (@vendor == current_user.vendor && current_user.permission_class.admin)
        @permission_classes = PermissionClass.all.where(vendor: @vendor)
    end

    def edit
        @vendor = Vendor.find(params[:id])
        return redirect_to '/' unless (@vendor == current_user.vendor && current_user.permission_class.admin)
    end

    def update
        vendor = Vendor.find(params[:id])
        return render :edit unless vendor.update(vendor_params)
        redirect_to vendor_path(vendor)
    end
    
    def create
        @vendor = Vendor.new(vendor_params)
        return  render :new unless @vendor.save
        @user =  User.new(user_params.merge(vendor: @vendor, permission_class_id: @vendor.permission_classes.first.id))
        return  render :new unless @user.save
        session[:user_id] = @user.id
        redirect_to '/'
    end

    private

    def vendor_params
        params.require(:vendor).permit(:name, :address, :url, :phone_number, :contact_email)
    end

    def user_params
        params.require(:user).permit(:username, :first_name, :last_name, :password, :password_confirmation)
    end

end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/edit.html.erb
<%= form_for @vendor do |f| %>
  <h3>Vendor Info</h3>
    <%=f.label :name%><br>
    <%=f.text_field :name%><br>

    <%=f.label :address%><br>
    <%=f.text_field :address%><br>

    <%=f.label :website %><br>
    <%=f.url_field :url%><br>

    <%=f.label :phone_number %><br>
    <%=f.telephone_field :phone_number%><br>

    <%=f.label :email %><br>
    <%=f.email_field :contact_email %><br>
    <br>
    <%= f.submit %>
<%end%>

app/views/vendors/new.erb
<% if @current_user.errors.any? %>
  <ul class= "alert alert-danger">
    <% @current_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<% if @vendor.errors.any? %>
  <ul class= "alert alert-danger">
    <% @vendor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for vendors_path, url: vendors_path do |f| %>
  <h3>Vendor Info</h3>
  <%=fields_for :vendor, @vendor do |vendor_field|%>
    <%=vendor_field.label :name%><br>
    <%=vendor_field.text_field :name%><br>

    <%=vendor_field.label :address%><br>
    <%=vendor_field.text_field :address%><br>

    <%=vendor_field.label :website %><br>
    <%=vendor_field.url_field :url%><br>

    <%=vendor_field.label :phone_number %><br>
    <%=vendor_field.telephone_field :phone_number%><br>

    <%=vendor_field.label :email %><br>
    <%=vendor_field.email_field :contact_email %><br>
  <%end%>
  <br>

  <h3>Owner Info </h3>
  <%=fields_for :user do |user_field|%>
    <%=user_field.label :username %><br>
    <%=user_field.text_field :username%><br>

    <%=user_field.label :first_name %><br>
    <%=user_field.text_field :first_name%><br>

    <%=user_field.label :last_name %><br>
    <%=user_field.text_field :last_name%><br>

    <%=user_field.label :password %><br>
    <%=user_field.password_field :password%><br>

    <%=user_field.label :password_confirmation %><br>
    <%=user_field.password_field :password_confirmation%><br>
  <%end%>
  <br>

  <%=f.submit "Submit"%>
<%end%>

app/views/vendors/show.html.erb
<div class="container-fluid float-left">
    <div class="row">
        <div class="col-lg-6">
            <table class="table table-striped table-bordered table-sm">
                <caption style='caption-side: top'>Vendor Info</caption>
                <tr>
                    <td>Name</td>
                    <td><%= @vendor.name %></td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td><%= @vendor.address %></td>
                </tr>
                <tr>
                    <td>Website:</td>
                    <td><%= @vendor.url %></td>
                </tr>
                <tr>
                    <td>Phone Number:</td>
                    <td><%= @vendor.phone_number %></td>
                </tr>
                <tr>
                    <td>Contact Email:</td>
                    <td><%= @vendor.contact_email %></td>
                </tr>
            </table>
            <%= link_to 'Edit Vendor', edit_vendor_path(@vendor) %>
        </div>
        <div class="col-lg-6">
            <table class="table table-striped table-bordered table-sm">
                <caption style='caption-side: top'>Job Titles</caption>
                <% @permission_classes.each do |pc| %>
                    <tr>
                        <td><%= pc.title %></td>
                        <td><%= link_to 'edit', edit_permission_class_path(pc) %></td>
                        <td><% if pc.users.count == 0%>
                        <%= link_to 'delete', permission_class_path(pc), method: 'delete' %>
                        <% end %></td>
                    </tr>
                <% end %>
            </table>
            <%= link_to 'Add Job Title', new_permission_class_path %><br>
            <%= link_to 'Edit Employee Titles', '/permission_classes' %>

        </div>
    </div>
</div>