config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :permission_classes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :technician_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment_bookings, only: [:new, :create, :destroy], path_names: {new: 'new/:show_id' }
  resources :equipment
  resources :shows
  resources :vendors, only: [:new, :create, :edit, :update, :show]
  resources :sessions, only: [:new ,:destroy]
  resources :users
  
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  post '/equipment_bookings/:id' => 'equipment_bookings#increment'
  post '/users/set_permissions' => 'users#set_permissions'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/show.rb
class Show < ApplicationRecord
    belongs_to :vendor
    has_many :equipment_bookings
    has_many :equipment, through: :equipment_bookings
    has_many :technician_bookings
    has_many :users, through: :technician_bookings

    validates :name, :venue, :client, :start, :end, presence: true
    validates_uniqueness_of :name
    def start_display
        self.start.localtime.strftime("%b %-d %Y %l:%M %p")
    end

    def end_display
        self.end.localtime.strftime("%b %-d %Y %l:%M %p")
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    before_action :can_create_show, only: [:new, :create, :edit, :destroy]
    
    def index
        @shows = current_user.vendor.shows.order(:start)
    end

    def show
        @show = Show.find(params[:id])
        return redirect_to shows_path unless @show.vendor == current_user.vendor
    end

    def new
        @show = Show.new(start: Time.now, end: Time.now)
    end

    def create
        @show = Show.new(show_params.merge(vendor: current_user.vendor))
        return render :new unless @show.save
        redirect_to shows_path
    end

    def edit
        @show = Show.find(params[:id])
        return redirect_to shows_path unless @show.vendor == current_user.vendor
    end

    def update
        @show = Show.find(params[:id])
        @show.update(show_params)
        redirect_to show_path(@show)
    end

    def destroy
        @show = Show.find(params[:id])
        @show.destroy
        redirect_to shows_path
    end

    private

    def show_params
        params.require(:show).permit(:name, :venue, :client, :start, :end)
    end

    def can_create_show
        if !current_user.permission_class.create_show
        flash[:alert] = "You dont have permission to access show records"
        return redirect_to request.referrer unless request.referrer == nil
        redirect_to '/'
        end
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/edit.html.erb
<% if @show.errors.any? %>
        <ul class= "alert alert-danger">
          <% @show.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

<h3>Add show to schedule:</h3>
<%= form_for @show do |f| %>
    <%=f.label :name %><br>
    <%=f.text_field :name %><br>

    <%=f.label :venue %><br>
    <%=f.text_field :venue %><br>

    <%=f.label :client %><br>
    <%=f.text_field :client %><br>

    <%=f.label :start %><br>
    <%=f.datetime_field :start %><br>

    <%=f.label :end %><br>
    <%=f.datetime_field :end %><br>

    <%=f.submit "Submit"%>
<% end %>

app/views/shows/index.html.erb
<% if !flash[:alert].nil? %> 
   <div class= "alert alert-danger">
   <%= flash[:alert] %>
   </div>
<% end %>

<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>Venue</th>
            <th>Client</th>
            <th>Start</th>
            <th>End</th>
        </tr>
    </thead>
    <tbody>
<% @shows.each do |s|%>
    <tr>
    <td><%= link_to s.name, show_path(s) %></td>
    <td> <%= s.venue %> </td>
    <td> <%= s.client %> </td>
    <td> <%= s.start_display %> </td>
    <td> <%= s.end_display %> </td>
    </tr>
<% end %>
    </tbody>
</table>
<%if @permission.create_show%>
<%= link_to 'Add Show', new_show_path %>
<%end%>

app/views/shows/new.html.erb
<% if @show.errors.any? %>
        <ul class= "alert alert-danger">
          <% @show.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

<h3>Add show to schedule:</h3>
<%= form_for @show do |f| %>
    <%=f.label :name %><br>
    <%=f.text_field :name %><br>

    <%=f.label :venue %><br>
    <%=f.text_field :venue %><br>

    <%=f.label :client %><br>
    <%=f.text_field :client %><br>

    <%=f.label :start %><br>
    <%=f.datetime_field :start %><br>

    <%=f.label :end %><br>
    <%=f.datetime_field :end %><br>

    <%=f.submit "Submit"%>
<% end %>

app/views/shows/show.html.erb
<% if !flash[:alert].nil? %> 
   <div class= "alert alert-danger">
   <%= flash[:alert] %>
   </div>
<% end %>

<table table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
        <tr>
            <th>Event</th>
            <th>Venue</th>
            <th>Client</th>
            <th>Start</th>
            <th>End</th>
            <%if @permission.create_show%>
            <th></th>
            <th></th>
            <%end%>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class='font-weight-bold'><%= @show.name %></td>
            <td><%= @show.venue %></td>
            <td><%= @show.client %></td>
            <td><%= @show.start_display %></td>
            <td><%= @show.end_display %></td>
            <%if @permission.create_show%>
            <td><%= button_to "Edit", edit_show_path(@show), method: 'get', class: 'btn btn-sm btn-info' %></td>
            <td><%= button_to "Delete", show_path(@show), {method: "delete", data: { confirm: "Are you sure you want to delete #{@show.name}?"}, class: 'btn btn-sm btn-danger' }%></td>            
            <%end%>
        </tr>
    </tbody>
</table>
<div class="container-fluid float-left">
    <div class="row">
        <div class="col-lg-6">
            <table table class="table table-striped table-bordered table-sm">
            <caption style='caption-side: top'>Equipment Required</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Equipment Name</th>
                    <th>Category</th>
                    <th>Sub-Category</th>
                    <th>Quantity</th>
                    <%if @permission.book_equipment%>
                    <th></th>
                    <%end%>
                </tr>
                </thead>
                <% unless @show.equipment.empty? %>
                <tbody>
                <% @show.equipment_bookings.each do |e|%>
                <tr>
                    <td><%= link_to "#{e.equipment.name}", equipment_path(e.equipment) %></td>
                    <td><%= e.equipment.category %></td>
                    <td><%= e.equipment.sub_category %></td>
                    <td>
                        <div style="float: left; width: auto;">
                        <%= button_to '-', equipment_booking_path(e), params: {increment: -1}, disabled: e.quantity_min?, class: 'btn btn-sm btn-outline-secondary' %>
                        </div>
                        <div style="float: left; width: auto; margin: 3px;">
                        <%= e.quantity %>
                        </div>
                        <div style="float: left; width: auto;">
                        <%= button_to '+', equipment_booking_path(e), params: {increment: 1}, disabled: e.quantity_max?,  class: 'btn btn-sm btn-outline-secondary'%>
                        </div>
                    </td>
                    <%if @permission.book_equipment%>
                    <td><%= button_to 'Delete', equipment_booking_path(e), method: 'delete', class: 'btn btn-sm btn-danger' %></td>
                    <%end%>
                </tr>
                <% end %>
                </tbody>
                <% end %>
            </table>
            <%if @permission.book_equipment%>
            <%= link_to 'Add equipment to Show', "/equipment_bookings/new/#{@show.id}" %>
            <%end%>
        </div>
        <div class="col-lg-6">
            <table class="table table-striped table-bordered table-sm">
            <caption style='caption-side: top'>Event Staff</caption>
                <thead  class="thead-dark">
                <tr>
                    <th>Technician</th>
                    <th>Call Time</th>
                    <th>Out Time</th>
                    <%if @permission.book_technician%>
                    <th></th>
                    <%end%>
                </tr>
                </thead>
                <% unless @show.users.empty? %>
                <tbody>
                <% @show.technician_bookings.each do |t|%>
                <tr>
                    <td><%= link_to t.user.full_name, user_path(t.user) %></td>
                    <td><%= t.call_time_display %></td>
                    <td><%= t.out_time_display %></td>
                    <%if @permission.book_technician%>
                    <td><%= button_to 'Delete', technician_booking_path(t), method: 'delete', class: 'btn btn-sm btn-danger' %></td>
                    <%end%>
                </tr>
                <% end %>
                </tbody>
                <% end %>
            </table>
            <%if @permission.book_technician%>
            <%= link_to 'Add staff to Show', "/technician_bookings/new/#{@show.id}" %>
            <%end%>
        </div>
    </div>
</div>